package com.example.dagger2androidapplication.car;

import android.util.Log;

public class Tires {
    // Third party class therefore, cannot annotate with @Inject

    private static final String TAG = "Car"; // generated by logt

    public void inflate(){
        Log.d(TAG, "Tires inflated");
    }
}
